
name: Build and deploy
permissions:
  contents: write

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm test
    - run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/teste-actions
        retention-days: 1

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: dist/teste-actions      
