
name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm install && npm run build
    
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
        retention-days: 1
        
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git checkout gh-pages
    - run: ls -l
    - uses: actions/download-artifact@v3.0.0
      with:
        name: dist
        path: .
        
    - name: Commit files
      run: |
        git config --local user.email "andreneves3@gmail.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add deploy files" -a
