
name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cd star-wars && npm install && npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: dist/star-wars

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
        retention-days: 1